const AVAILABLE_PERMISSIONS = Object.freeze([
  "products.view",
  "products.create",
  "products.edit",
  "products.delete",
  "categories.view",
  "categories.create",
  "categories.edit",
  "categories.delete",
  "hsn_tax.view",
  "hsn_tax.create",
  "hsn_tax.edit",
  "hsn_tax.delete",
  "inventory.view",
  "inventory.adjust",
  "inventory.edit_policy",
  "inventory.view_movements",
  "inventory.view_low_stock",
  "search.view",
  "search.manage_synonyms",
  "search.manage_phrase_mappings",
  "search.manage_keywords",
  "search.manage_redirects",
  "search.reindex",
  "search.view_logs",
  "catalogue.import",
  "catalogue.export",
  "orders.view",
  "orders.create",
  "orders.edit",
  "orders.cancel",
  "orders.export",
  "payments.view",
  "payments.verify_manual",
  "payments.refund",
  "invoices.view",
  "invoices.generate",
  "invoices.download",
  "invoices.edit_buyer_details",
  "invoices.export_tally",
  "shipping.view",
  "shipping.create",
  "shipping.manage_config",
  "shipping.update_tracking",
  "shipping.mark_delivered",
  "shipping.upload_pod",
  "customers.view",
  "customers.edit",
  "customers.mark_dealer",
  "reviews.view",
  "reviews.moderate",
  "reviews.delete",
  "partners.view",
  "partners.manage",
  "print_jobs.view",
  "print_jobs.moderate",
  "reports.view",
  "reports.export",
  "blogs.view",
  "blogs.create",
  "blogs.edit",
  "blogs.delete",
  "job_vacancies.view",
  "job_vacancies.create",
  "job_vacancies.edit",
  "job_vacancies.delete",
  "website_leads.view",
  "website_leads.edit",
  "marketing.view",
  "marketing.edit_offers",
  "marketing.edit_templates",
  "settings.view",
  "settings.edit",
  "settings.custom_code",
  "staff.view",
  "staff.create",
  "staff.edit_permissions"
]);

const DEFAULT_PERMISSION_GROUPS = Object.freeze([
  {
    id: "group_super_admin",
    name: "Super Admin",
    slug: "super-admin",
    description: "Full platform access.",
    isSystem: true,
    permissions: ["*"]
  },
  {
    id: "group_ops_staff",
    name: "Operations Staff",
    slug: "operations-staff",
    description: "View-only baseline with limited updates.",
    isSystem: true,
    permissions: [
      "settings.view",
      "products.view",
      "categories.view",
      "inventory.view",
      "blogs.view",
      "website_leads.view",
      "search.view",
      "orders.view",
      "customers.view",
      "reports.view",
      "reviews.view"
    ]
  }
]);

module.exports = { AVAILABLE_PERMISSIONS, DEFAULT_PERMISSION_GROUPS };
